name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: Default
  vmImage: hosted-azure

variables:
  - group: aks

resources:
  repositories:
    - repository: Iac-template
      type: github
      endpoint: github.com_alexbaptista
      name: alexbaptista/azuredevops-iac-template-pipeline
      ref: refs/tags/v.1.5
  containers:
    - container: terraform
      image: docker.io/alxbap/azuredevops-iac-template-pipeline:v.1.5
      env:
        TF_STATE_BLOB_ACCOUNT_NAME: $(terraformStateBlobAccountName)
        TF_STATE_BLOB_CONTAINER_NAME: $(terraformStateBlobContainerName)
        TF_STATE_BLOB_FILE: $(terraformStateBlobFile)
        ARM_SUBSCRIPTION_ID: $(terraformArmSubscriptionId)
        ARM_CLIENT_ID: $(terraformArmClientId)
        ARM_CLIENT_SECRET: $(terraformArmClientSecret)
        ARM_TENANT_ID: $(terraformArmTenantId)
        TF_IN_AUTOMATION: 1
        TF_LOG: trace
        TF_LOG_PATH: terraform.log

trigger:
  branches:
    include:
      - refs/heads/main
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
      - refs/heads/main
  paths:
    exclude:
    - README.md

stages:
  - template: pipeline/terraform.yaml@Iac-template
    parameters:
      terraformPath: $(System.DefaultWorkingDirectory)/terraform
      terraformVersion: 1.3.0
      resourceContainer: terraform
      envConfig:
        DEV:
          environmentDeploy: dev-aks-cluster
          gitBranch: refs/heads/main
        PR:
          githubToken: $(githubToken)